### ISSUE TITLE
clang trunk pre-define ndrange_t in the compiler

### ISSUE THREAD

**Issue by aaronenyeshi** [KhronosGroup/SPIR#14]
Command Line:
clang -cc1 -x cl -cl-std=CL2.0 -include C:\llvmspirv\llvm\tools\clang\lib\Headers/opencl-20.h -emit-llvm -fblocks -triple spir64-unknown-unknown -o _temp_1_Tonga.clang.bc _temp_1_Tonga.i

Error Message:
In file included from <built-in>:305:
In file included from <command line>:1:
C:\llvmspirv\llvm\tools\clang\lib\Headers/opencl-20.h:11230:3: error: typedef redefinition with different types ('struct ndrange_t' vs 'ndrange_t')
} ndrange_t;

Likely cause: clang trunk pre-defines ndrange_t in the compiler

Possible Workaround: Remove the ndrange_t type definition in the header file

**Comment by bader** [comment]
aaronenyeshi, just removing ndrange_t from the header file will not work.
ndrange_t data type support was added to clang v3.9, but our current compiler is based on the v3.6.
Right solution would be adopting ndrange_t type support from clang v3.9 to the current SPIR-V compiler, but it will require additional work to preserve existing SPIR 2.0 LLVM format.

Possible Workaround could be implemented for the header that will go into ToT.

**Comment by yxsamliu** [comment]
Alexey, before the headers are upstreamed to clang trunk, here is the only place for users to get the header file.

Can we use LLVM version macro to conditionally define this ndrange_t here?

Thanks.

**Comment by yxsamliu** [comment]
Aaron may create a pull request for that.

**Comment by bader** [comment]
Fixed @ #15.
