### ISSUE TITLE
clang trunk requires cl_khr_int64_base_atomics to be enabled before atomic_long can be used in the header file

### ISSUE THREAD

**Issue by aaronenyeshi** [KhronosGroup/SPIR#16]
**Command Line:**
clang.exe -cc1 -x cl -cl-std=CL2.0 -include C:/llvmspirv/llvm/tools/clang/lib/Headers/opencl-20.h -emit-llvm -fblocks -triple spir64-unknown-unknown -o _test.bc test.i

**Error Messages:**
test.i:2:10: error: use of type 'atomic_long' (aka '_Atomic(long)') requires cl_khr_int64_base_atomics extension to be enabled
volatile atomic_long var;
         ^
test.i:2:10: error: use of type 'atomic_long' (aka '_Atomic(long)') requires cl_khr_int64_extended_atomics extension to be enabled
test.i:3:17: error: use of type 'atomic_long' (aka '_Atomic(long)') requires cl_khr_int64_base_atomics extension to be enabled
global volatile atomic_long g_var;
                ^
test.i:3:17: error: use of type 'atomic_long' (aka '_Atomic(long)') requires cl_khr_int64_extended_atomics extension to be enabled
test.i:4:10: error: use of type 'atomic_long' (aka '_Atomic(long)') requires cl_khr_int64_base_atomics extension to be enabled
volatile atomic_long a_var[2];
         ^
test.i:4:10: error: use of type 'atomic_long' (aka '_Atomic(long)') requires cl_khr_int64_extended_atomics extension to be enabled
test.i:5:17: error: use of type 'atomic_long' (aka '_Atomic(long)') requires cl_khr_int64_base_atomics extension to be enabled
global volatile atomic_long\* p_var;
                ^
test.i:5:17: error: use of type 'atomic_long' (aka '_Atomic(long)') requires cl_khr_int64_extended_atomics extension to be enabled
8 errors generated.

**Cause:** clang trunk requires cl_khr_int64_base_atomics and cl_khr_int64_extended_atomics to be enabled before atomic_long can be used in the header file

Testcase: 
[test.zip](https://github.com/KhronosGroup/SPIR/files/188177/test.zip)

**Comment by bader** [comment]
It looks like test issue. Initial state of all extensions is 'disabled' according to OpenCL extension specification. Data types used in the attached test case require enabling cl_khr_int64_extended_atomics  and cl_khr_int64_base_atomics extension. To do that, please add these two lines before declaring atomic variables to your test code to make it valid OpenCL code:

#pragma OPENCL EXTENSION cl_khr_int64_base_atomics : enable
#pragma OPENCL EXTENSION cl_khr_int64_extended_atomics : enable

See OpenCL kernel language specification V2.0 6.13.11.6 for more details.

**Comment by bader** [comment]
Aaron, are you okay to close that issue?

**Comment by aaronenyeshi** [comment]
Yes, thank you very much Alexey
