### ISSUE TITLE
clang trunk requires function prototype for atom_add and atom_or

### ISSUE THREAD

**Issue by aaronenyeshi** [KhronosGroup/SPIR#17]
**Command Line:**
clang -cc1 -x cl -cl-std=CL2.0 -include C:/llvmspirv/llvm/tools/clang/lib/Headers/opencl-20.h -emit-llvm -fblocks -triple spir64-unknown-unknown -o test.bc test.i
**Error Message:**
test.i:6:5: warning: implicit declaration of function 'atom_add' is invalid in C99
    atom_add(&dst[t_address], 1u);
    ^
test.i:6:5: error: function with no prototype cannot use the spir_function calling convention
test.i:7:5: warning: implicit declaration of function 'atom_or' is invalid in C99
    atom_or(&dst[t_address], 1u);
    ^
test.i:7:5: error: function with no prototype cannot use the spir_function calling convention
2 warnings and 2 errors generated.
**Cause:**
Requires function prototype for atom_add and atom_or.
**Testcase:**
[test.zip](https://github.com/KhronosGroup/SPIR/files/195919/test.zip)

**Comment by aaronenyeshi** [comment]
Same issue happens with atom_sub, atom_xchg, atom_min, atom_max, atom_inc, atom_dec, atom_cmpxchg, atom_and, atom_xor

**Comment by bader** [comment]
AFAIK, this issue was fixed in https://github.com/KhronosGroup/SPIR/commit/31e8d3fc5d58de1b25b2fd4050e0affd81220bdf
Could you try the latest version of the header, please?

**Comment by aaronenyeshi** [comment]
That is strange. I see this issue with a more recent header file (c36fab3). I've updated to latest version 3a3bbc7 and I can reproduce this issue.

**Comment by bader** [comment]
I think the problem here is in the command line.
Clang doesn't know which extensions are supported by the device we compile for, so user has to provide this information explicitly by defining corresponding macro. In your case we need to enable cl_khr_global_int32_base_atomics and cl_khr_global_int32_extended_atomics

I also tried to explain that in readme file: https://github.com/KhronosGroup/SPIR/blob/spirv-1.0/README.md

Could you try and let me know if it works for you?

**Comment by aaronenyeshi** [comment]
Thanks, seems that options cl_khr_global_int32_base_atomics and cl_khr_global_int32_extended_atomics were not working because of different naming. 

So options -Dcl_khr_int32_base_atomics and -Dcl_khr_int32_extended_atomics work. Thanks

**Comment by aaronenyeshi** [comment]
No issue here, just usage of the header file.
