### ISSUE TITLE
Error fetching SPIRV-1.1 branch?

### ISSUE THREAD

**Issue by oscarbg** [KhronosGroup/SPIR#28]
Hi,
just following the instructions in step:
  git checkout --track -b khronos/spirv-3.6.1 remotes/origin/khronos/spirv-3.6.1
I get
fatal: A branch named 'khronos/spirv-3.6.1' already exists.
is that OK?

**Comment by pierremoreau** [comment]
This is expected since the default branch of the repo SPIRV-LLVM is khronos/spirv-3.6.1, so when you cloned it, it automatically checked out that branch rather than master. If you run `git status`, it should say that you are on khronos/spirv-3.6.1.

**Comment by bader** [comment]
Initially default branch in SPIRV-LLVM repository was master branch and this command worked without errors.
Do you suggest update the README file?
I can replace exact git command with something like: "Checkout 'khronos/spirv-3.6.1' branch."

**Comment by pierremoreau** [comment]
You could also use `git clone -b khronos/spirv-3.6.1 https://github.com/KhronosGroup/SPIRV-LLVM.git llvm`, which will automatically checkout the given branch. That way, it will work regardless of the default branch.

**Comment by bader** [comment]
Oscar, README file in spirv-1.1 branch was updated. Could you confirm that new instructions work for you, please?

**Comment by oscarbg** [comment]
Yes it works!

2016-04-20 16:46 GMT+02:00 bader notifications@github.com:
