### ISSUE TITLE
Calls to Barrier are being incorrectly duplicated

### ISSUE THREAD

**Issue by pfimgtec** [KhronosGroup/SPIR#3]
The OpenCL builtin barrier must be guaranteed to be executed by all instances of a workgroup with the same arguments. Currently, the SPIR frontend is applying Control-Flow optimisations which break this guarantee on input programs. Consider:

__kernel void entry_point(
    __write_only image2d_t dst_image,
    __read_only  image2d_t src_image,
    __global const float2 *tileULs_g,
    __global const float4 *tileDxDy_g
) {
    __local float integral[10][10];

```
sampler_t samplerA = CLK_NORMALIZED_COORDS_TRUE | CLK_ADDRESS_CLAMP_TO_EDGE | CLK_FILTER_LINEAR;

int lid = get_local_id(0);
int bid = get_group_id(0);
float2 ids;
ids.x = lid;
ids.y = lid;

float2 tileUL = tileULs_g[bid];
float4 tileDxDy = tileDxDy_g[bid];
int2 tileOut = (int2){(bid % ARRAYTILES) * TILESIZE, (bid / ARRAYTILES) * TILESIZE};

if (lid<10) {
    tileUL += ids*tileDxDy.xy;
    float sum = 0;
    for(int i=0; i<TILESIZE; ++i){
        sum += read_imagef( src_image, samplerA, tileUL).x;
        integral[i][lid] = sum;
        tileUL += tileDxDy.zw;
    }
}

// The Barrier here is unconditional
barrier(CLK_LOCAL_MEM_FENCE);

if (lid<10){
    float sum=0;
    for(int i=0; i<TILESIZE; ++i){
        sum+=integral[lid][i];
        write_imagef(dst_image, tileOut + (int2){i, lid}, sum);
    }
}
```

}

The SPIR output from this file is changed so that the semantics of the input program are like this:

(code trimmed for brevity)
if (lid<10) {
    tileUL += ids*tileDxDy.xy;
    float sum = 0;
    for (int i=0; i<TILESIZE; ++i) {
        sum += read_imagef( src_image, samplerA, tileUL).x;
        integral[i][lid] = sum;
        tileUL += tileDxDy.zw;

```
    // Duplicated call
    barrier(CLK_LOCAL_MEM_FENCE);

float sum=0;
for(int i=0; i<TILESIZE; ++i){//add up rows
    sum+=integral[lid][i];
    write_imagef(dst_image, tileOut + (int2){i, lid}, sum);
}
```

}
else
{
    // Duplicated call
    barrier(CLK_LOCAL_MEM_FENCE);
}

In more modern versions of clang/llvm, the barrier function can be applied the **attribute**((noduplicate)) which prevents this sort of optimisations from being performed.

Adding -O0 to the build options appears to fix the issue, so that's a potential work-around.

**Comment by dneto0** [comment]
I agree!  That's a serious bug.  It can convert a perfectly good kernel into one that can lock up.
However, I'm not involved with this project.  :-(

**Comment by bader** [comment]
Implemented a workaround in https://github.com/KhronosGroup/SPIR/commit/fd090c876dd8fff6c788e48628b4fc851c5c7228.
-O0 is default optimization level and other optimization levels that enable invalid optimizations are disabled.
