### ISSUE TITLE
How to compile an OpenCL2.0 kernel cl file into spir-v 1.0?

### ISSUE THREAD

**Issue by ncybmh99** [KhronosGroup/SPIR#32]
I clone the spir-v 1.0 branch and build the clang binary. I want to use it to compile some OpenCL2.0 cl file into the spir-v 1.0 format:

clang -cc1 -emit-spirv -triple=spir-unknown-unknown -cl-std=CL2.0 -include opencl_spir.h test_pipe_workgroup_readwrite_int.cl

And it shows some syntax error 

test_pipe_workgroup_readwrite_int.cl:7:6: error: implicit declaration of function 'is_valid_reserve_id' is invalid in OpenCL
  if(is_valid_reserve_id(res_id))
     ^
1 error generated.

I suppose it should include some header file defining those OpenCL2.0 kernel built-ins. Is there a header file available? Where can I find it? 

The only one I can find is for the SPIR (https://github.com/KhronosGroup/SPIR-Tools/blob/master/headers/opencl_spir.h), I guess it only defines OpenCL 1.2 built-ins.

Thanks.

**Comment by pierremoreau** [comment]
From the [Readme.md](https://github.com/KhronosGroup/SPIR/blob/spirv-1.0/README.md) file: `clang -cc1 -emit-spirv -triple=spir-unknown-unknown -cl-std=CL2.0 -include opencl.h kernel.cl -o kernel.spir`, so it should be `-include opencl.h` and not `-include opencl_spir.h`. If you are using spirv-1.0, you should read the README from that branch, not from the spir-12 branch. ;-) EDIT: it looks like you took a mix of both, which instructions did you use?
_Note that SPIR-V is not an update of SPIR: it is a new intermediate language._

**Comment by ncybmh99** [comment]
I knew the README says to use "opencl.h". But, "opencl.h" is the header file for the host APIs, not for the kernel APIs. Isn't it?

I tried to use "-include opencl.h". It generates the same error of "test_pipe_workgroup_readwrite_int.cl:7:6: error: implicit declaration of function 'is_valid_reserve_id' is invalid in OpenCL".

**Comment by ncybmh99** [comment]
I used the README from https://github.com/KhronosGroup/SPIR/tree/spirv-1.0. I write a very simple kernel.cl as:

__kernel void test() 
{
  reserve_id_t id;

  bool result = is_valid_reserve_id(id);
}

clang -cc1 -emit-spirv -triple=spir-unknown-unknown -cl-std=CL2.0 -include opencl.h kernel.cl -o kernel.spir

And it shows:

kernel.cl:5:17: error: implicit declaration of function 'is_valid_reserve_id' is invalid in OpenCL
  bool result = is_valid_reserve_id(id);
                ^
1 error generated.

**Comment by ncybmh99** [comment]
Please note "bool is_valid_reserve_id(reserve_id_t)" is a OpenCL2.0 Spec-defined built-in.

**Comment by bader** [comment]
ncybmh99, this is a bug in clang. Pipe built-in functions implemented in the clang and this one is missing.

**Comment by ncybmh99** [comment]
Hi bader,

Not only that pipe built-in, but also some basic types are missing.

__kernel void test(__global int4\* in, __global int4\* out) 
{
  out[0] = in[0];
} 

$clang -cc1 -emit-llvm -triple=spir-unknown-unknown -cl-std=CL2.0 -include opencl.h kernel.cl 

kernel.cl:1:29: error: unknown type name 'int4'; did you mean 'int'?
__kernel void test(__global int4\* in, __global int4\* out) 
                            ^~~~
                            int
kernel.cl:1:48: error: unknown type name 'int4'; did you mean 'int'?
__kernel void test(__global int4\* in, __global int4\* out) 
                                               ^~~~
                                               int
2 errors generated.

Where are those Opencl types (e.g. int4) declared? They are not in the Khronos opencl.h, are they?

**Comment by bader** [comment]
Vector types are defined in opencl.h built with clang. It's located here: https://github.com/KhronosGroup/SPIR/blob/spirv-1.0/lib/Headers/opencl.h

Probably there is another opencl.h in the search paths.

**Comment by ncybmh99** [comment]
Thanks. It works to include https://github.com/KhronosGroup/SPIR/blob/spirv-1.0/lib/Headers/opencl.h

**Comment by bader** [comment]
I guess is_valid_reserve_id is still missing. Correct?

**Comment by pierremoreau** [comment]
`is_valid_reserve_id` is in (and I guess it already was at the time, as it was in 3bf67794b9b694045caac16b4df8a3617ad0e434). Kernel from comment 3 compiles fine now.

**Comment by bader** [comment]
@ncybmh99, can we close the issue?
