### ISSUE TITLE
There is a bug of "get_image_width"

### ISSUE THREAD

**Issue by ncybmh99** [KhronosGroup/SPIR#53]
Given a 1.2 kernel as image.cl

__kernel void testWriteui(__global uchar *src, write_only image2d_t dstimg)
{
    int    tid_x = get_global_id(0);
    int    tid_y = get_global_id(1);
    int    indx = tid_y \* get_image_width(dstimg) + tid_x;
    uint4       color;

```
indx *= 4;
     color.x = (uint)src[indx+0];
     color.y = (uint)src[indx+1];
     color.z = (uint)src[indx+2];
     color.w = (uint)src[indx+3];
write_imageui(dstimg, (int2)(tid_x, tid_y), color);
```

}

clang -cc1 -emit-spirv  -triple=spir-unknown-unknown -cl-std=CL1.2 -include opencl.h image.cl

image.cl:5:27: error: no matching function for call to 'get_image_width'
    int    indx = tid_y \* get_image_width(dstimg) + tid_x;
                          ^~~~~~~~~~~~~~~
opencl.h:15380:48: note: candidate function not viable: no known conversion from '**write_only image2d_t' to '__read_only image1d_t' for 1st argument
int __const_func __attribute**((overloadable)) get_image_width(image1d_t image);
                                               ^
opencl.h:15381:48: note: candidate function not viable: no known conversion from '**write_only image2d_t' to '__read_only image1d_buffer_t' for 1st argument
int __const_func __attribute**((overloadable)) get_image_width(image1d_buffer_t image);
                                               ^
opencl.h:15382:48: note: candidate function not viable: no known conversion from '**write_only image2d_t' to '__read_only image2d_t' for 1st argument
int __const_func __attribute**((overloadable)) get_image_width(image2d_t image);
                                               ^
opencl.h:15383:48: note: candidate function not viable: no known conversion from '**write_only image2d_t' to '__read_only image3d_t' for 1st argument
int __const_func __attribute**((overloadable)) get_image_width(image3d_t image);
                                               ^
opencl.h:15384:48: note: candidate function not viable: no known conversion from '**write_only image2d_t' to '__read_only image1d_array_t' for 1st argument
int __const_func __attribute**((overloadable)) get_image_width(image1d_array_t image);
                                               ^
opencl.h:15385:48: note: candidate function not viable: no known conversion from '**write_only image2d_t' to '__read_only image2d_array_t' for 1st argument
int __const_func __attribute**((overloadable)) get_image_width(image2d_array_t image);
                                               ^
1 error generated.

"get_image_width" with a write_only image is valid, isn't it?

**Comment by yxsamliu** [comment]
This is because image type without explicit access qualifier is treated as read_only.

Probably we should update opencl.h with opencl-c.h in Clang trunk, which includes write_only/read_write image types for image functions.
