### ISSUE TITLE
Is it a bug? "'half' cannot be used as the type of a kernel parameter"?

### ISSUE THREAD

**Issue by ncybmh99** [KhronosGroup/SPIR#54]
Given a 1.2 kernel as t.cl
# pragma OPENCL EXTENSION cl_khr_fp16 : enable

kernel void half_scalar_d(half halfd,
                          const half consthalfd,
                          private half privatehalfd,
                          private const half privateconsthalfd)
{}

clang -cc1 -emit-spirv  -triple=spir-unknown-unknown -cl-std=CL1.2 -include opencl.h t.cl

t.cl:3:32: error: 'half' cannot be used as the type of a kernel parameter
kernel void half_scalar_d(half halfd,
                               ^
t.cl:4:38: error: 'const half' cannot be used as the type of a kernel parameter
                          const half consthalfd,
                                     ^
t.cl:5:40: error: 'half' cannot be used as the type of a kernel parameter
                          private half privatehalfd,
                                       ^
t.cl:6:46: error: 'const half' cannot be used as the type of a kernel parameter
                          private const half privateconsthalfd)
                                             ^
4 errors generated.

**Comment by dneto0** [comment]
Kernels can't take arguments of type "half".  See OpenCL C 2.0 spec, section 6.9 paragraph k.
The extension cl_khr_fp16 does not remove that restriction.

**Comment by yxsamliu** [comment]
The extension allows half to be used as a function parameter. Since its size is platform independent, there is really no reason to forbid it as a kernel argument. Probably the extension spec should be revised to explicitly allow half as kernel argument.

**Comment by dneto0** [comment]
> Since its size is platform independent, there is really no reason to forbid it as a kernel argument.

Size might not be the only issue.  Calling conventions for kernels could be different from regular functions.

Revising the extension is not the right route, since an application written against the "new" version might not run on an implementation written against the current version.  Instead, you'd have to make a new extension (with different name) to support this feature.

**Comment by yxsamliu** [comment]
Isn't a new extension solely to allow half type as kernel argument an overkill?

The spec does not define the calling convention for kernel. It only defines an API function to pass an argument for a kernel. How a kernel gets an argument is implementation detail. For most implementations, host code put kernel argument to a specific GPU memory and kernel load it from there. Passing a half argument to kernel and passing a short argument to kernel is not different.

**Comment by dneto0** [comment]
You'd have to take this up at the OpenCL working group.

**Comment by bsochack** [comment]
David, are you looking at the latest version of OpenCL C spec?
https://www.khronos.org/registry/cl/specs/opencl-2.0-openclc.pdf 

> k. Arguments to kernel functions in a program cannot be declared with the built-in scalar
> types bool, size_t, ptrdiff_t, intptr_t, and uintptr_t or a struct and/or
> union that contain fields declared to be one of these built-in scalar types. The size in
> bytes of these types are implementation-defined and in addition can also be different for
> the OpenCL device and the host processor making it difficult to allocate buffer objects to
> be passed as arguments to a kernel declared as pointer to these types.
> 
> l. half is not supported as half can be used as a storage format26 only and is not a data
> type on which floating-point arithmetic can be performed.
> 
> 26 Unless the cl_khr_fp16 extension is supported and has been enabled"

**Comment by dneto0** [comment]
@bsochack I missed that footnote!  In that case it seems it would make sense to update the cl_khr_fp16 extension to clarify by explicitly saying it's allowed.  But you'd still have to check with other implementors at the OpenCL working group to make sure they implemented it.  I have no idea if the conformance suite covers this case.  But it should.

**Comment by bader** [comment]
It's not a bug for OpenCL C v1.2 compiler.
https://www.khronos.org/registry/cl/specs/opencl-1.2.pdf still restricts using half as a kernel function argument type:

> k. Arguments to kernel functions in a program cannot be declared with the built-in scalar
> types bool, **half**, size_t, ptrdiff_t, intptr_t, and uintptr_t or a struct
> and/or union that contain fields declared to be one of these built-in scalar types. The size
> in bytes of these types except half are implementation-defined and in addition can also
> be different for the OpenCL device and the host processor making it difficult to allocate
> buffer objects to be passed as arguments to a kernel declared as pointer to these types.
> half is not supported as half can be used as a storage format47 only and is not a data
> type on which floating-point arithmetic can be performed.
