### ISSUE TITLE
some functions in opencl-20.h failed to compile due to empty parameter list

### ISSUE THREAD

**Issue by yxsamliu** [KhronosGroup/SPIR#8]
I was trying to compile some cl kernels with Clang but I got these errors:

C:\p4\stg_win50\git-llvm\llvm\tools\clang\lib\Headers/opencl-20.h:11271:13: error: function with no prototype cannot use the spir_function calling convention
clk_event_t create_user_event();
            ^
C:\p4\stg_win50\git-llvm\llvm\tools\clang\lib\Headers/opencl-20.h:11279:9: error: function with no prototype cannot use the spir_function calling convention
queue_t get_default_queue();
        ^
C:\p4\stg_win50\git-llvm\llvm\tools\clang\lib\Headers/opencl-20.h:11585:38: error: function with no prototype cannot use the spir_function calling convention
size_t **attribute**((overloadable)) get_global_linear_id();
                                     ^
C:\p4\stg_win50\git-llvm\llvm\tools\clang\lib\Headers/opencl-20.h:11585:38: error: 'overloadable' function 'get_global_linear_id' must have a prototype
C:\p4\stg_win50\git-llvm\llvm\tools\clang\lib\Headers/opencl-20.h:11586:38: error: function with no prototype cannot use the spir_function calling convention
size_t **attribute**((overloadable)) get_local_linear_id();

seems clang does not like function declarations with empty parameter list. Add void to that should fix it.

**Comment by bader** [comment]
Sam, could you attach the kernel you are trying to compile and command line you are using, please?

**Comment by yxsamliu** [comment]
The command line I use is

clang -cc1 -x cl -fblocks -cl-std=CL2.0 -include opencl-20.h -emit-llvm -triple spir64-unknown-unknown a.cl

a.cl is an empty file

**Comment by bader** [comment]
Interesting. I can't reproduce that diagnostics. Do you use spirv-1.0 branch? Do apply any modifications to clang?

**Comment by yxsamliu** [comment]
I am using Clang ToT with the header from spirv-1.0 branch.

**Comment by bader** [comment]
I just committed https://github.com/KhronosGroup/SPIR/commit/5ec5d7e32a8cb837f1115c8e595cc8a95e9ddb38. Could you verify that it fixes your problem, please?
I don't have Clang ToT at hand.

**Comment by yxsamliu** [comment]
Thanks. it fixes this issue. There are some other issues using the header file with clang ToT but I will open separate issues.
